### ISSUE TITLE
Getting gateway added to vendor list?

### ISSUE THREAD

**Issue by shawaj** [brocaar/lora-gateway-os#10]
Hi there,

What's the process to get our gateway added here - https://www.loraserver.io/lora-gateway-os/overview/

Thanks,
Aaron

**Comment by brocaar** [comment]
That depends on the platform. E.g. when it is a completely new platform, we would need to add a new BSP layer (`layers/bsp`) and prepare the Mender patches for the bootloader (found under `layers/targets`).

But I assume you're talking about adding support for: https://uk.pi-supply.com/products/iot-lora-gateway-hat-for-raspberry-pi?

In that case, the Raspberry Pi platform is already supported and this would require:

- [ ] Add concentrator shield: https://github.com/brocaar/lora-gateway-os/blob/master/layers/targets/meta-raspberrypi/recipes-core/gateway-config/gateway-config/gateway-config.sh
- [ ] Include concentrator specific config: https://github.com/brocaar/lora-gateway-os/blob/master/layers/targets/meta-raspberrypi/recipes-lora/lora-packet-forwarder/lora-packet-forwarder_%25.bbappend
- [ ] Potentially include packet-forwarder modifications?

**Comment by shawaj** [comment]
@brocaar yes that is the Gateway HAT we are talking about.

CC @ryanteck - can you sort the other bits?

**Comment by ryanteck** [comment]
Hi @brocaar ,

Yes it is Raspberry Pi based, as it uses the RAK833 which is the same semtech chipset as the ic880a, RAK831 etc.

I've tested it out by selecting ic880a and it worked fine. The GPIO pin used is BCM22 for reset.

We'd be looking for it to have two regions that they can select from either EU868 or US915.

Would you like me to try and figure out what parts to change and do a git pull request?

- Ryan

**Comment by brocaar** [comment]
@ryanteck that would be great :-)

**Comment by ryanteck** [comment]
Hi @brocaar ,

I believe I've done the changes however haven't been able to test yet. If you can just look through to see if I have done it correctly.

Thanks

**Comment by brocaar** [comment]
Thanks @ryanteck :+1: I've provided some feedback in the PR (tiny changes).

**Comment by brocaar** [comment]
@ryanteck @shawaj anything I can help with to get your pull-request (https://github.com/brocaar/lora-gateway-os/pull/13) merged? It hasn't been updated for a while. @ryanteck are you still working on this?

**Comment by ryanteck** [comment]
Hi @brocaar, was the new PR all fine?

**Comment by brocaar** [comment]
Closing this issue as the PR has already been merged :slightly_smiling_face:
