### ISSUE TITLE
no ethernet with test4-image

### ISSUE THREAD

**Issue by toepi** [brocaar/lora-gateway-os#11]
want try out mender upgrade and so I flashed test2 to my raspberrypi3 b+. After upgrade it to test4 via a mender (URL: https://artifacts.loraserver.io/downloads/lora-gateway-os/raspberrypi/raspberrypi3/2.0.0test4/) and a reboot it lost the ethernet connection, back to test2 ethernet was there again.

**Comment by brocaar** [comment]
I'm trying to reproduce your issue as I have not seen this before.

**Comment by brocaar** [comment]
I've:

- [x] Flashed a Raspberry Pi 3 with the base test2 image
- [x] Scanned with `nmap` which IP was assigned (wired) using DHCP
- [x] Used mender to update to the base test4 image
- [x] Successfully logged in again using SSH using the IP of the Raspberry Pi

I don't see any issue with regards to lost ethernet connection.

**Comment by toepi** [comment]
strange, same workflow her. okay use a local console instead of nmap for determine assigned ip.

have extra switch back to test2 to check if I've destroy the configuration. and after it flash again to test4 ... with no success. will try it again and will report it her again.

**Comment by brocaar** [comment]
I will order a RPi 3 B+ to see if there is any difference between B and B+.

**Comment by martinoorlandi** [comment]
Any success anyone?

I have the same issue of no ethernet connection with both images test2 and test4 using a RPi 3B+ with a RAK2245 hat.

It works fine if connected to a HMDI monitor, if I try to boot without it, it doesn't seem to work...not sure if it does not boot at all or just doesn't get an IP address assigned.

**Comment by brocaar** [comment]
I still can not reproduce the issue with a Raspberry Pi 3B+. See #9 .

**Comment by martinoorlandi** [comment]
Thanks! this Is what I tried: (https://github.com/brocaar/lora-gateway-os/issues/9#issuecomment-507756921)

**Comment by brocaar** [comment]
This should be fixed by https://github.com/brocaar/lora-gateway-os/issues/9.
